const input = document.querySelector('.js-input')
const button = document.querySelector('.js-button')
const list = document.querySelector('.js-list')
const remove = document.querySelector('.js-delete')

button.addEventListener('click', function () {
  let val = input.value
  if (input.value == '') {
  } else {
    input.value = ''
    list.insertAdjacentHTML("afterbegin", `
    <li class="todo__item js-item">
      <div class="todo__item-container">
        ${val}
      </div>
      <div class="todo__item-remove js-delete"><?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16" viewBox="0 0 16 16">
<path fill="currentColor" d="M8 0c-4.4 0-8 3.6-8 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zM12.2 10.8l-1.4 1.4-2.8-2.8-2.8 2.8-1.4-1.4 2.8-2.8-2.8-2.8 1.4-1.4 2.8 2.8 2.8-2.8 1.4 1.4-2.8 2.8 2.8 2.8z"></path>
</svg></div>
    </li>
    `)
  }
})

document.body.addEventListener('click', function (event) {
  const target = event.target.closest('.js-delete');
  const item = event.target.closest('.js-item')
  if (!target) return;

    item.remove()

});
